version: "3"
services:
  webservice:
    image: simple-proxy
    container_name: "simple-proxy"
    build:
      context: .
      target: simple-proxy
    environment:
      - NODE_ENV=production
      - PROXY_KEY_FILE=/app/.keys
      - PROXY_PORT=8000
      - PROXY_MAX_LISTENERS=0
      - REMOTE_HOST=google.com
      - REMOTE_PORT=80
      - PROXY_WORKERS=4
    ports:
      - 8000:8000
    stdin_open: true
